[package]
name = "advent2018"
version = "0.1.0"
authors = ["Mateus Rodrigues Costa <mateusrodcosta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day01"

[[bin]]
name = "day02"
